# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import list_pb2 as protos_dot_list__pb2


class TodoListStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddTodo = channel.unary_unary(
                '/TodoList/AddTodo',
                request_serializer=protos_dot_list__pb2.AddTodoRequest.SerializeToString,
                response_deserializer=protos_dot_list__pb2.AddTodoResponse.FromString,
                )
        self.RemoveTodo = channel.unary_unary(
                '/TodoList/RemoveTodo',
                request_serializer=protos_dot_list__pb2.RemoveTodoRequest.SerializeToString,
                response_deserializer=protos_dot_list__pb2.RemoveTodoResponse.FromString,
                )
        self.FetchTodos = channel.unary_unary(
                '/TodoList/FetchTodos',
                request_serializer=protos_dot_list__pb2.FetchTodosRequest.SerializeToString,
                response_deserializer=protos_dot_list__pb2.FetchTodosResponse.FromString,
                )
        self.UpdateTodo = channel.unary_unary(
                '/TodoList/UpdateTodo',
                request_serializer=protos_dot_list__pb2.UpdateTodoRequest.SerializeToString,
                response_deserializer=protos_dot_list__pb2.Todo.FromString,
                )


class TodoListServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddTodo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveTodo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchTodos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTodo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TodoListServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTodo,
                    request_deserializer=protos_dot_list__pb2.AddTodoRequest.FromString,
                    response_serializer=protos_dot_list__pb2.AddTodoResponse.SerializeToString,
            ),
            'RemoveTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveTodo,
                    request_deserializer=protos_dot_list__pb2.RemoveTodoRequest.FromString,
                    response_serializer=protos_dot_list__pb2.RemoveTodoResponse.SerializeToString,
            ),
            'FetchTodos': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchTodos,
                    request_deserializer=protos_dot_list__pb2.FetchTodosRequest.FromString,
                    response_serializer=protos_dot_list__pb2.FetchTodosResponse.SerializeToString,
            ),
            'UpdateTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTodo,
                    request_deserializer=protos_dot_list__pb2.UpdateTodoRequest.FromString,
                    response_serializer=protos_dot_list__pb2.Todo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TodoList', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TodoList(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TodoList/AddTodo',
            protos_dot_list__pb2.AddTodoRequest.SerializeToString,
            protos_dot_list__pb2.AddTodoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TodoList/RemoveTodo',
            protos_dot_list__pb2.RemoveTodoRequest.SerializeToString,
            protos_dot_list__pb2.RemoveTodoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FetchTodos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TodoList/FetchTodos',
            protos_dot_list__pb2.FetchTodosRequest.SerializeToString,
            protos_dot_list__pb2.FetchTodosResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TodoList/UpdateTodo',
            protos_dot_list__pb2.UpdateTodoRequest.SerializeToString,
            protos_dot_list__pb2.Todo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
