# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protos/user.proto\"[\n\x11\x43reateUserRequest\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"\x1a\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\x05\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1e\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\"#\n\x12ValidateJWTRequest\x12\r\n\x05token\x18\x01 \x01(\t\"5\n\x13ValidateJWTResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x32\xa0\x01\n\x0bUserService\x12/\n\nCreateUser\x12\x12.CreateUserRequest\x1a\r.UserResponse\x12&\n\x05Login\x12\r.LoginRequest\x1a\x0e.LoginResponse\x12\x38\n\x0bValidateJWT\x12\x13.ValidateJWTRequest\x1a\x14.ValidateJWTResponseb\x06proto3')



_CREATEUSERREQUEST = DESCRIPTOR.message_types_by_name['CreateUserRequest']
_USERRESPONSE = DESCRIPTOR.message_types_by_name['UserResponse']
_LOGINREQUEST = DESCRIPTOR.message_types_by_name['LoginRequest']
_LOGINRESPONSE = DESCRIPTOR.message_types_by_name['LoginResponse']
_VALIDATEJWTREQUEST = DESCRIPTOR.message_types_by_name['ValidateJWTRequest']
_VALIDATEJWTRESPONSE = DESCRIPTOR.message_types_by_name['ValidateJWTResponse']
CreateUserRequest = _reflection.GeneratedProtocolMessageType('CreateUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEUSERREQUEST,
  '__module__' : 'protos.user_pb2'
  # @@protoc_insertion_point(class_scope:CreateUserRequest)
  })
_sym_db.RegisterMessage(CreateUserRequest)

UserResponse = _reflection.GeneratedProtocolMessageType('UserResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERRESPONSE,
  '__module__' : 'protos.user_pb2'
  # @@protoc_insertion_point(class_scope:UserResponse)
  })
_sym_db.RegisterMessage(UserResponse)

LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREQUEST,
  '__module__' : 'protos.user_pb2'
  # @@protoc_insertion_point(class_scope:LoginRequest)
  })
_sym_db.RegisterMessage(LoginRequest)

LoginResponse = _reflection.GeneratedProtocolMessageType('LoginResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOGINRESPONSE,
  '__module__' : 'protos.user_pb2'
  # @@protoc_insertion_point(class_scope:LoginResponse)
  })
_sym_db.RegisterMessage(LoginResponse)

ValidateJWTRequest = _reflection.GeneratedProtocolMessageType('ValidateJWTRequest', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATEJWTREQUEST,
  '__module__' : 'protos.user_pb2'
  # @@protoc_insertion_point(class_scope:ValidateJWTRequest)
  })
_sym_db.RegisterMessage(ValidateJWTRequest)

ValidateJWTResponse = _reflection.GeneratedProtocolMessageType('ValidateJWTResponse', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATEJWTRESPONSE,
  '__module__' : 'protos.user_pb2'
  # @@protoc_insertion_point(class_scope:ValidateJWTResponse)
  })
_sym_db.RegisterMessage(ValidateJWTResponse)

_USERSERVICE = DESCRIPTOR.services_by_name['UserService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEUSERREQUEST._serialized_start=21
  _CREATEUSERREQUEST._serialized_end=112
  _USERRESPONSE._serialized_start=114
  _USERRESPONSE._serialized_end=140
  _LOGINREQUEST._serialized_start=142
  _LOGINREQUEST._serialized_end=189
  _LOGINRESPONSE._serialized_start=191
  _LOGINRESPONSE._serialized_end=221
  _VALIDATEJWTREQUEST._serialized_start=223
  _VALIDATEJWTREQUEST._serialized_end=258
  _VALIDATEJWTRESPONSE._serialized_start=260
  _VALIDATEJWTRESPONSE._serialized_end=313
  _USERSERVICE._serialized_start=316
  _USERSERVICE._serialized_end=476
# @@protoc_insertion_point(module_scope)
